### PR TITLE
feat: added splash screen

### PR DESCRIPTION
**Pull request by V9vek**
📝 **Description**

I have used new Splash API `1.0.0` to show the Splash Screen
**Link**: https://developer.android.com/develop/ui/views/launch/splash-screen/migrate

📷 **Sample**

https://user-images.githubusercontent.com/40730402/194554569-937650af-1ba0-4212-abc8-63770d713ca3.mp4

❤ If you feel the PR solves the issue, please merge it and added the required `hacktoberfest` tags

### CODE REVIEW

**Comment by poseidon2060** [comment]
hey @V9vek did you happen to get the following error when running the app?
`Class content provided for type descriptor me.ilker.dota2compose.ui.teams.TeamsKt$teamDetails$1$1$1$1 actually defines class me.ilker.dota2compose.ui.teams.TeamsKt$TeamDetails$1$1$1$1`

if yes what did you do to solve it?

**Comment by V9vek** [comment]
> hey @V9vek did you happen to get the following error when running the app? `Class content provided for type descriptor me.ilker.dota2compose.ui.teams.TeamsKt$teamDetails$1$1$1$1 actually defines class me.ilker.dota2compose.ui.teams.TeamsKt$TeamDetails$1$1$1$1`
> 
> if yes what did you do to solve it?

yes, I got that error
the error meant that 2 functions were having same name, so I just changed the name of `TeamDetails` fun to `TeamDetails2`

**Comment by ilkeraslan** [comment]
> > hey @V9vek did you happen to get the following error when running the app? `Class content provided for type descriptor me.ilker.dota2compose.ui.teams.TeamsKt$teamDetails$1$1$1$1 actually defines class me.ilker.dota2compose.ui.teams.TeamsKt$TeamDetails$1$1$1$1`
> > if yes what did you do to solve it?
> 
> yes, I got that error the error meant that 2 functions were having same name, so I just changed the name of `TeamDetails` fun to `TeamDetails2`
> 
> @ilkeraslan we were getting the above error mentioned by @poseidon2060 , so I changed the name of the function for the time being, if you want some changes, do let me know blush

Hey @V9vek that looks great! I wonder why the repository allowed you to commit the `.idea` and `build` files as they should be included in `.gitignore`, but I was wondering if we can remove these from the PR?

**Comment by V9vek** [comment]
Okay @ilkeraslan I will open the new PR with changes in gitignore file
I am closing this 👍🏻

**Comment by V9vek** [comment]
@ilkeraslan I tried adding buildSrc/build folder to `gitignore` and opened a new PR, but it is still adding those build files no matter what

**Pull request closed without merging**
